[package]
name = "lazytickets"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
directories = "6.0.0"
fuzzy-matcher = "0.3.7"
ratatui = "0.30.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "process", "time", "sync"] }
toml = "1.1.3"
